Xpetra: CMake config I don't understand why, but it looks like having an ELSE condition to disable macro is important. I run into a disturbing problem where Epetra=OFF but HAVE_EPETRA is defined in Xpetra_config.hpp
For the records:

Trilinos_ENABLE_Epetra=OFF
Trilinos_ENABLE_EpetraExt=""
Trilinos_ENABLE_Tpetra=ON

-
-
-

In file included from /home/jngaida/dev/MueLu/src/preCopyrightTrilinos/muelu/xpetra/src/Utils/Xpetra_Utils.hpp:4,
                 from /home/jngaida/dev/MueLu/src/preCopyrightTrilinos/muelu/xpetra/src/Utils/Xpetra_Utils.cpp:1:
/home/jngaida/dev/MueLu/src/preCopyrightTrilinos/muelu/xpetra/src/Def/Xpetra_ConfigDefs.hpp:40:29: error: Xpetra_config.hpp: No such file or directory
Linking CXX static library libmuelu.a
[ 78%] Built target muelu-utils
In file included from /home/jngaida/dev/MueLu/src/preCopyrightTrilinos/muelu/xpetra/src/Utils/Xpetra_EpetraUtils.cpp:1:
/home/jngaida/dev/MueLu/src/preCopyrightTrilinos/muelu/xpetra/src/Def/Xpetra_ConfigDefs.hpp:40:29: error: Xpetra_config.hpp: No such file or directory
In file included from /home/jngaida/dev/MueLu/src/preCopyrightTrilinos/muelu/xpetra/src/Platform/Xpetra_DefaultPlatform.cpp:1:
/home/jngaida/dev/MueLu/src/preCopyrightTrilinos/muelu/xpetra/src/Def/Xpetra_ConfigDefs.hpp:40:29: error: Xpetra_config.hpp: No such file or directory
[ 78%] Built target muelu
make[2]: *** [preCopyrightTrilinos/muelu/xpetra/src/CMakeFiles/muelu-xpetra.dir/Utils/Xpetra_EpetraUtils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [preCopyrightTrilinos/muelu/xpetra/src/CMakeFiles/muelu-xpetra.dir/Utils/Xpetra_Utils.cpp.o] Error 1
make[2]: *** [preCopyrightTrilinos/muelu/xpetra/src/CMakeFiles/muelu-xpetra.dir/Platform/Xpetra_DefaultPlatform.cpp.o] Error 1
make[1]: *** [preCopyrightTrilinos/muelu/xpetra/src/CMakeFiles/muelu-xpetra.dir/all] Error 2
make: *** [all] Error 2

-
-
-

Configuring Trilinos build directory

-- TRILINOS_HOME_DIR = /home/jngaida/dev/MueLu/src
-- TRILINOS_BUILD_DIR = /home/jngaida/dev/MueLu/build/muelu-serial-debug-tpetra
-- CMAKE_VERSION = 2.8.6
PYTHON_EXECUTABLE = /usr/bin/python2.4

Setting up major user options ...

Reading the list of extra repositories from /home/jngaida/dev/MueLu/src/cmake/ExtraExternalRepositories.cmake

Reading the list of packages from /home/jngaida/dev/MueLu/src/cmake/TrilinosPackages.cmake

-- Trilinos_NUM_PACKAGES='59'

Reading the list of TPLs from /home/jngaida/dev/MueLu/src/cmake/TrilinosTPLs.cmake

-- Trilinos_NUM_TPLS='58'

Processing Dependencies.cmake files and buliding internal dependencies graph

-- Trilinos_NUM_SE_PACKAGES='88'
-- Tentatively enabling TPL 'Pthread'
-- Tentatively enabling TPL 'BinUtils'

Dumping the XML dependencies file /home/jngaida/dev/MueLu/src/cmake/python/data/TrilinosPackageDependencies.xml ...

Dumping the HTML dependencies webpage file /home/jngaida/dev/MueLu/src/cmake/python/data/TrilinosPackageDependenciesTable.html ...

Dumping the CDash XML dependencies file /home/jngaida/dev/MueLu/src/cmake/python/data/CDashSubprojectDependencies.xml ...

Reading a list of extra packages from /home/jngaida/dev/MueLu/src/preCopyrightTrilinos/ExtraTrilinosPackages.cmake ...

-- Trilinos_NUM_PACKAGES='65'

Reading a list of extra TPLs from /home/jngaida/dev/MueLu/src/preCopyrightTrilinos/ExtraTrilinosTPLs.cmake ...

-- Trilinos_NUM_TPLS='58'

Processing Dependencies.cmake files and buliding internal dependencies graph

-- Trilinos_NUM_SE_PACKAGES='94'
-- Tentatively enabling TPL 'Pthread'
-- Tentatively enabling TPL 'BinUtils'

Explicitly enabled packages on input (by user):  Tpetra Amesos2 Belos Ifpack2 MueLu 5

Explicitly enabled SE packages on input (by user):  Tpetra Amesos2 Belos Ifpack2 MueLu 5

Explicitly disabled packages on input (by user or by default):  Epetra Trios Meros Phdmesh Aristos ForTrilinos WebTrilinos NewPackage ShyLU Stalix Lyno MeshingGenie Zoltan2 13

Explicitly disabled SE packages on input (by user or by default):  Epetra Trios Meros Phdmesh Aristos ForTrilinos WebTrilinos NewPackage ShyLU Stalix Lyno MeshingGenie Zoltan2 13

Explicitly enabled TPLs on input (by user):  Pthread 1

Explicitly disabled TPLs on input (by user or by default):  BinUtils MPI 2

Disabling all packages that have a required dependency on disabled TPLs and optional package TPL support based on TPL_ENABLE_<TPL>=OFF ...

Disabling forward required packages and optional intra-package support that have a dependancy on disabled packages Trilinos_ENABLE_<PACKAGE>=OFF ...

-- Setting Trilinos_ENABLE_Triutils=OFF because Triutils has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_EpetraExt=OFF because EpetraExt has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_ThyraEpetraAdapters=OFF because ThyraEpetraAdapters has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_ThyraEpetraExtAdapters=OFF because ThyraEpetraExtAdapters has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Isorropia=OFF because Isorropia has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Pliris=OFF because Pliris has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Claps=OFF because Claps has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_AztecOO=OFF because AztecOO has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Galeri=OFF because Galeri has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Amesos=OFF because Amesos has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Ifpack=OFF because Ifpack has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Komplex=OFF because Komplex has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_RBGen=OFF because RBGen has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_TriKota=OFF because TriKota has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Moertel=OFF because Moertel has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Stokhos=OFF because Stokhos has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Piro=OFF because Piro has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_Sundance=OFF because Sundance has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_CTrilinos=OFF because CTrilinos has a required library dependence on disabled package Epetra
-- Setting Trilinos_ENABLE_FEApp=OFF because FEApp has a required library dependence on disabled package Epetra
-- Setting Tpetra_ENABLE_Epetra=OFF because Tpetra has an optional library dependence on disabled package Epetra
-- Setting Amesos2_ENABLE_Epetra=OFF because Amesos2 has an optional library dependence on disabled package Epetra
-- Setting Belos_ENABLE_Epetra=OFF because Belos has an optional library dependence on disabled package Epetra
-- Setting MueLu_ENABLE_Epetra=OFF because MueLu has an optional library dependence on disabled package Epetra
-- Setting Ifpack2_ENABLE_TESTS=OFF because Ifpack2 has a required test/example dependence on disabled package Triutils
-- Setting Ifpack2_ENABLE_EXAMPLES=OFF because Ifpack2 has a required test/example dependence on disabled package Triutils
-- Setting Amesos2_ENABLE_EpetraExt=OFF because Amesos2 has an optional library dependence on disabled package EpetraExt
-- Setting MueLu_ENABLE_EpetraExt=OFF because MueLu has an optional library dependence on disabled package EpetraExt
-- Setting Trilinos_ENABLE_Stratimikos=OFF because Stratimikos has a required library dependence on disabled package ThyraEpetraAdapters
-- Setting Trilinos_ENABLE_Teko=OFF because Teko has a required library dependence on disabled package ThyraEpetraAdapters
-- Setting MueLu_ENABLE_Amesos=OFF because MueLu has an optional library dependence on disabled package Amesos
-- Setting MueLu_ENABLE_Ifpack=OFF because MueLu has an optional library dependence on disabled package Ifpack

Enabling all packages that are not disabled based on <PACKAGE>_ENABLE_<DEPPACKAGE>=ON  ...

Enabling all remaining required packages for the current set of enabled packages ...

-- Setting Trilinos_ENABLE_Teuchos=ON because Trilinos_ENABLE_MueLu=ON
-- Setting Trilinos_ENABLE_Kokkos=ON because Trilinos_ENABLE_Ifpack2=ON

Enabling all optional intra-package enables <PACKAGE>_ENABLE_<DEPPACKAGE> that are not currently disabled if both sets of packages are enabled ...

-- Setting Belos_ENABLE_Tpetra=ON since Trilinos_ENABLE_Belos=ON AND Trilinos_ENABLE_Tpetra=ON
-- Setting MueLu_ENABLE_Amesos2=ON since Trilinos_ENABLE_MueLu=ON AND Trilinos_ENABLE_Amesos2=ON
-- Setting MueLu_ENABLE_Belos=ON since Trilinos_ENABLE_MueLu=ON AND Trilinos_ENABLE_Belos=ON
-- Setting MueLu_ENABLE_Kokkos=ON since Trilinos_ENABLE_MueLu=ON AND Trilinos_ENABLE_Kokkos=ON
-- Setting MueLu_ENABLE_Ifpack2=ON since Trilinos_ENABLE_MueLu=ON AND Trilinos_ENABLE_Ifpack2=ON
-- Setting MueLu_ENABLE_Tpetra=ON since Trilinos_ENABLE_MueLu=ON AND Trilinos_ENABLE_Tpetra=ON

Enabling all remaining required TPLs for current set of enabled packages ...

-- Setting TPL_ENABLE_BLAS=ON because it is required by the enabled package Teuchos
-- Setting TPL_ENABLE_LAPACK=ON because it is required by the enabled package Teuchos

Enabling all optional package TPL support for currently enabled TPLs ...

Enabling TPLs based on <PACKAGE>_ENABLE_<TPL>=ON if TPL is not explicitly disabled ...

-- Setting TPL_ENABLE_SuperLU=ON because Amesos2_ENABLE_SuperLU=ON

Set cache entries for optional packages/TPLs and tests/examples for packages actually enabled ...

Enabling all packages not yet enabled that have at least one subpackage enabled ...

Final set of enabled packages:  Teuchos Kokkos Tpetra Amesos2 Belos Ifpack2 MueLu 7

Final set of enabled SE packages:  Teuchos Kokkos Tpetra Amesos2 Belos Ifpack2 MueLu 7

Final set of non-enabled packages:  TrilinosFramework ThreadPool Sacado RTOp Epetra Zoltan Shards GlobiPack Triutils EpetraExt Thyra OptiPack Isorropia Pliris Claps AztecOO Galeri Amesos Pamgen SEACAS Trios Ifpack Komplex ML Stratimikos Meros FEI Anasazi Teko RBGen TriKota Intrepid STK Phalanx Phdmesh NOX Moertel TrilinosCouplings Rythmos MOOCHO Aristos Stokhos Piro Sundance CTrilinos ForTrilinos PyTrilinos WebTrilinos Didasko NewPackage Optika Mesquite FEApp ShyLU Stalix Lyno MeshingGenie Zoltan2 58

Final set of non-enabled SE packages:  TrilinosFramework ThreadPool Sacado RTOp Epetra Zoltan Shards GlobiPack Triutils EpetraExt ThyraCore ThyraEpetraAdapters ThyraEpetraExtAdapters ThyraTpetraAdapters Thyra OptiPack Isorropia Pliris Claps AztecOO Galeri Amesos Pamgen SEACASExodus SEACASExodus_for SEACASNemesis SEACASIoss SEACASChaco SEACASAprepro_lib SEACASSupes SEACASSuplib SEACASAlgebra SEACASAprepro SEACASConjoin SEACASEjoin SEACASEpu SEACASExo2mat SEACASExodiff SEACASExomatlab SEACASExotxt SEACASGjoin SEACASGrope SEACASMapvar SEACASMapvar-kd SEACASMat2exo SEACASNemslice SEACASNemspread SEACASTxtexo SEACAS Trios Ifpack Komplex ML Stratimikos Meros FEI Anasazi Teko RBGen TriKota Intrepid STK Phalanx Phdmesh NOX Moertel TrilinosCouplings Rythmos MOOCHO Aristos Stokhos Piro Sundance CTrilinos ForTrilinos PyTrilinos WebTrilinos Didasko NewPackage Optika Mesquite FEApp ShyLU Stalix Lyno MeshingGenie Zoltan2 87

Final set of enabled TPLs:  Pthread BLAS LAPACK SuperLU 4

Final set of non-enabled TPLs:  Peano CUDA Thrust Cusp TBB BinUtils ARPREC QD MPI Boost Scotch METIS ParMETIS PaToH CppUnit ADOLC ADIC TVMET MF ExodusII Nemesis XDMF Netcdf y12m SuperLUDist SuperLUMT Zlib UMFPACK MA28 AMD PETSC HYPRE BLACS SCALAPACK MUMPS PARDISO_MKL Oski TAUCS ForUQTK Dakota HIPS HDF5 MATLAB CASK SPARSKIT QT gtest BoostLib OpenNURBS Portals CrayPortals Gemini Pablo Pnetcdf 54

Probing the environment ...

-- CMAKE_BUILD_TYPE='DEBUG'
-- CMAKE_C_COMPILER_ID='GNU'
-- CMAKE_CXX_COMPILER_ID='GNU'
-- Trilinos_HOSTNAME='magret.sandia.gov'
-- CMAKE_HOST_SYSTEM_NAME='Linux'

Getting information for all enabled TPLs ...

-- Processing enabled TPL: Pthread
--   Attempting to enable tentatively enabled TPL 'Pthread' ...
--   TPL_Pthread_LIBRARIES='/usr/lib64/libpthread.so'
--   TPL_Pthread_INCLUDE_DIRS='/usr/include'
--   Attempt to enable tentatively enabled TPL 'Pthread' passed!
-- Processing enabled TPL: BLAS
--   TPL_BLAS_LIBRARIES='-lblas'
--   TPL_BLAS_INCLUDE_DIRS=''
-- Processing enabled TPL: LAPACK
--   TPL_LAPACK_LIBRARIES='-llapack'
--   TPL_LAPACK_INCLUDE_DIRS=''
-- Processing enabled TPL: SuperLU
--   TPL_SuperLU_LIBRARIES='/home/jngaida/opt/stow/superlu/4.1/lib64/libsuperlu_4.1.a'
--   TPL_SuperLU_INCLUDE_DIRS='/home/jngaida/opt/stow/superlu/4.1/include'

Setting up testing support ...

-- CTEST_DROP_METHOD='http'
-- CTEST_DROP_SITE='testing.sandia.gov'
-- CTEST_PROJECT_NAME='Trilinos'
-- CTEST_DROP_LOCATION='/cdash/submit.php?project=Trilinos'
-- CTEST_TRIGGER_SITE=''
-- CTEST_DROP_SITE_CDASH='TRUE'

Configuring individual enabled Trilinos packages ...

Processing enabled package: Teuchos (Libs)
Processing enabled package: Kokkos (Libs)
Processing enabled package: Tpetra (Libs)
Processing enabled package: Amesos2 (Libs)
Processing enabled package: Belos (Libs)
Processing enabled package: Ifpack2 (Libs)
Processing enabled package: MueLu (Libs, Tests, Examples)

Exporting library dependencies ...

Finished configuring Trilinos!

-- Configuring done
-- Generating done
-- Build files have been written to: /home/jngaida/dev/MueLu/build/muelu-serial-debug-tpetra