(From Sierra) Work around pathscale compiler bug.
The pathscale compiler was generating an undefined reference to __tcf_10
when a variable definition was in a section of unreachable code.  Moved
some code around so the variable is now legitimately used and only the
"return" statement is unreachable.

Build/Test Cases Summary
Enabled Packages: STK, Teuchos
Enabled all Forward Packages
0) MPI_DEBUG => passed: passed=1081,notpassed=0 (38.94 min)
1) SERIAL_RELEASE => passed: passed=1050,notpassed=0 (25.13 min)
Other local commits for this build/test group: 3e2ae9c, ae76e02