zoltan2: fix missing typename error with llvm/15.0.7
resolves error with llvm/15.0.7 Serial Debug builds:
```
Trilinos-pristine/packages/zoltan2/core/src/input/Zoltan2_TpetraCrsGraphAdapter.hpp:84:1: error: missing 'typename' prior to dependent type name 'TpetraCrsGraphAdapter<User, UserCoord>::Base::IdsDeviceView'
TpetraCrsGraphAdapter<User, UserCoord>::Base::IdsDeviceView
```

Signed-off-by: Nathan Ellingwood <ndellin@sandia.gov>