Fixing Teuchos Comm tests on Mac with GCC 4.4.2 (bug 4464)
On the Mac machine s903186 with the GCC 4.4.2 compiler, it generated
the build error:

In file included from /Users/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/teuchos/src/Teuchos_DefaultComm.hpp:35,
                 from /Users/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/teuchos/test/Comm/DefaultMpiComm_UnitTests.cpp:6:
/Users/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/teuchos/src/Teuchos_DefaultMpiComm.hpp: In member function 'void Teuchos::MpiComm<Ordinal>::reduceAllAndScatter(const Teuchos::ValueTypeReductionOp<Ordinal, char>&, Ordinal, const char*, const Ordinal*, char*) const [with Ordinal = char]':
/Users/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/teuchos/test/Comm/DefaultMpiComm_UnitTests.cpp:763:   instantiated from here
/Users/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/teuchos/src/Teuchos_DefaultMpiComm.hpp:387: error: array subscript has type 'char'
make[3]: *** [packages/teuchos/test/Comm/CMakeFiles/Teuchos_DefaultMpiComm_UnitTests.dir/DefaultMpiComm_UnitTests.cpp.o] Error 1
make[2]: *** [packages/teuchos/test/Comm/CMakeFiles/Teuchos_DefaultMpiComm_UnitTests.dir/all] Error 2
make[1]: *** [packages/teuchos/test/Comm/CMakeFiles/Teuchos_DefaultMpiComm_UnitTests.dir/rule] Error 2
make: *** [packages/teuchos/test/Comm/CMakeFiles/Teuchos_DefaultMpiComm_UnitTests.dir/rule] Error 2

The root of the problem is that the unit tests were using a char as an
ordinal.  This is silly.  No-one will ever use an char as an ordinal.
In fact, Teuchos::Comm should not even be templated on an Ordinal type
(see bug 4662).  To give similar testing, I replaced testing with char
with instead testing with short (int).

Now the code builds and runs just fine on this machine.

=============================
Build/Test Cases Summary
=============================

Fri Jun  4 14:02:35 MDT 2010

Enabled Packages: Teuchos

Build test results:
-------------------
0) MPI_DEBUG => passed: Trilinos/MPI_DEBUG: passed=57,notpassed=0 (1.36459430059 min)
1) SERIAL_RELEASE => passed: Trilinos/SERIAL_RELEASE: passed=54,notpassed=0 (1.49296125174 min)

Local commits for this build/test group:
----------------------------------------
223f04c Fixing Teuchos Comm tests on Mac with GCC 4.4.2 (bug 4464)
94b4da9 Removed some bad comments
f52d2ab Adding missing isnaninf for short int.