This gets rid of an ambiguous overload due to atomic_compare_exchange_strong being defined on Windows, in both Kokkos_Atomic_Windows.hpp and Kokkos_Atomic_Compare_Exchange_Strong.hpp.  It is not clear to me which should be kept.  This solution if's out the one in Kokkos_Atomic_Compare_Exchange_Strong.hpp, but perhaps, since std::atomic_compare_exchange_strong is part of C++11, one can code identically for Windows and non-Windows and just pull out Kokkos_Atomic_Windows.hpp?  Need feedback on this.
Now down to two errors:

D:\winsame\cary\vorpalall-dev3\Trilinos\packages\amesos2\src/Amesos2_Superlu_def.hpp(762,18): error: no member named 'LargeDiag' in namespace 'SLU'
D:\winsame\cary\vorpalall-dev3\Trilinos\packages\epetra\src\Epetra_SerialComm.h(83,42): error: allocating an object of abstract class type 'Epetra_SerialComm'