Teuchos: Add missing explicit instantiation for getEnvironmentVariable()
Without this explicit instaniation, I get the following link errors on my build of Trilinos:

<path>/bin/ld: packages/teuchos/core/src/libteuchoscore.a(Teuchos_SystemInformation.cpp.o): in function `Teuchos::SystemInformation::collectSystemInformation[abi:cxx11]()':
<bash>/Trilinos/packages/teuchos/core/src/Teuchos_SystemInformation.cpp:263:(.text+0x153a): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Teuchos::getEnvironmentVariable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::basic_string_view<char, std::char_traits<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'

When I add this explicit instantiation, this error goes away.