Piro: Mitigate compile error involving Piro_RythmosSolver
Commit 073e096190aaa0846a8ec10032fb940efab66304 resulted
in a compile error in Drekar:

piro/src/Piro_RythmosSolver_Def.hpp>:983:70: error:
"RythmosStepperFactory" was not declared in this scope

This commit isolates the 4 argument template in an ifdef
specific to Albany.