Windows: remove obsolete winmath.h
This TriBITS-distributed file seems to have been necessary at some point
in the distant past for successful Windows builds, but it now causes
build errors:
```
D:\nfr\scale\TriBITS\tribits\win_interface\include\winmath.h(155): error: function "tgammal" has already been defined

  inline long double tgammal(long double z){
```

Without the winmath includes, Intrepid successfully builds on MSVC 2015
(with an older Trilinos version) and 2017.