Normalize URLs to allow for git@ protocol in check
This allows for developers to use a git@ protocol for these repos instead of
the HTTPs protocol so they can do development on these GenConfig repos not
still be able to run the get_dependencies.sh script.  This just makes
development and testing easier.  Otherwise, you have to switch back and forth
between different sets of repos, which is error-prone and clunky.

I also reformatted the error message some to make more clear (IMHO).

I tested this manually in the following scenarios:

1) Starting with old GenConfig repo with wrong URL.  That gave the error message:

  ERROR: Current remote origin does not match expected!
     Current Remote:  git@gitlab-ex.sandia.gov:trilinos-devops-consolidation/code/GenConfig.git
     Expected Remote: https://github.com/sandialabs/GenConfig.git

  Please remove/move '/scratch/rabartl/Trilinos.base/Trilinos/packages/framework/GenConfig' and re-run this script

2) Starting with no GenConfig repo.  That gave seemed to clone the repos
correctly.

3) With existing GenConfig repo pointing to the correct URL.  This seemed to
update the repos correctly.

4) With existing GenConfig repo pointing to the correct URL but now with git@
URL instead of https:// URL and wrong SHA1 for GenConfig repo.  This seemed to
update the repos correctly.

NOTE: The new utility script `normalize_git_repo_url.py` is maintained with
unit tests in the little internal repo:

* https://gitlab-ex.sandia.gov/rabartl/normalize_git_repo_url

That makes this reusable for other such purposes in other projects as well.

Signed-off-by: Roscoe A. Bartlett <rabartl@sandia.gov>