zoltan2: replace use of char* code with std::string with istringstream
Replace the use of char* code with a std::string in the readChacoGraphHeaderInfo routine

This resolves compilation errors with cuda/12.4+gcc/13.2.0 with c++20:
```
/home/ndellin/Trilinos/packages/zoltan2/test/core/unit/input/XpetraMultiVectorInput.cpp(179): error: no operator ">>" matches these operands
            operand types are: std::basic_istream<char, std::char_traits<char>> >> char *
    issHeader >> nIDs >> nEdges >> code;
```

The `char* code` variable is not used outside of the readChacoGraphHeaderInfo routine, so it was removed from the function signature and the corresponding input variable were removed as well, replaced by use of `std::string s_code` variable within the routine to receive the istringstream input and for comparison (via c_str())