- Removed explicit usage of Teuchos::RCP, rcp, dyn_cast, const_rcp_cast, rcpFromRef, etc - Added type ROL::SharedPointer and methods ROL::makeShared and ROL::makeSharedFromRef,   ROL::staticPointerCast, ROL::dynamicPointerCast, ROL::constPointerCast.
  Usage

  // Example static object instantiation
  ObjectType obj(args);

  // Dynamically allocate an object and manage with a shared pointer
  ROL::SharedPointer<ObjectType> obj_ptr = ROL::makeShared<ObjectType>(args);

  // Create shared pointer to an existing object from a reference to it
  ROL::SharedPointer<ObjectType> pobj_ref = ROL::makeSharedFromRef(obj);

- The implementation of the SharedPointer type and related methods will depend on
  which version of ROL_SharedPointer.hpp is used

  rol/src/compatibility/teuchos/rcp/ROL_SharedPointer.hpp is the header to be
  included by default when building with ROL's CMake utilities. In this scenario,
  SharedPointer is an alias for Teuchos::RCP and the creation and casting methods
  invoke the analogous Teuchos method which have been used in ROL since its inception.

  The current alternative definition is in

  rol/src/compatibility/std/shared_ptr/ROL_SharedPointer.hpp

  which aliases the C++11 std::shared_ptr type.

  Building with the std::shared_ptr implementation is enabled by configuring CMake
  with the line

  -D ROL_ENABLE_STD_SHARED_PTR:BOOL=ON

- Added a build flag ENABLE_PYROL for building Python extensions with ROL. Currently,
  the only change involving this flag is that by defining ENABLE_PYROL, ROL::Vector
  will inherit from std::enable_shared_from_this, which will make sharing resources
  between Python and C++ easier.

  Reference:
  http://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html (Item 2)

  http://en.cppreference.com/w/cpp/memory/enable_shared_from_this

- Testing status: Currently. all of the examples and tests build and pass at 100%
  using gcc 7.2/clang 4 when using the default RCP implementation (no flag). Need
  to test with flag.
- The problem-specific parts of adapters/PDEOPT were compiled and debugged, however, I can
  not build everything on the machine I have been using due to the build error:

  ../teuchos/kokkoscompat/src/KokkosCompat_Details_KokkosInit.cpp:79:24: error: ‘ref’ is not a member of ‘std’

  After committing, I will check the build on a machine known to build PDEOPT. It
  is possible there are a couple of places where the std::shared_ptr implementation
  may have trouble: Anywhere where Teuchos::SerialDenseSolver is used, the setVectors
  and setMatrix methods expects objects of RCP type and these specific tests/examples
  may need to revert to explicit use of Teuchos::RCP. There are also places where
  Teuchos::ArrayRCP is used and compatibility may be an issue here as well.