shylubasker: add missing Teuchos_ScalarTraits.hpp
The header was needed when `Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON` to resolve errors of type
`Trilinos/packages/shylu/shylu_node/basker/src/shylubasker_scalar_traits.hpp:124:36: error: 'ScalarTraits' is not a member of 'Teuchos'`

Signed-off-by: Nathan Ellingwood <ndellin@sandia.gov>