ML: remove commented include which errors with Intel
With the intel compiler I got following error:
[ 67%] Building C object packages/ml/src/CMakeFiles/ml.dir/Utils/ml_memory.c.o
icc: command line warning #10006: ignoring unknown option '-Wno-pragmas'
In file included from /home/crtrott/Trilinos/packages/ml/src/Smoother/ml_smoother.h(44),
                 from /home/crtrott/Trilinos/packages/ml/src/Main/ml_1level.h(34),
                 from /home/crtrott/Trilinos/packages/ml/src/Operator/ml_operator.h(33),
                 from /home/crtrott/Trilinos/packages/ml/src/Utils/ml_utils.h(35),
                 from /home/crtrott/Trilinos/packages/ml/src/Utils/ml_memory.c(17):
/home/crtrott/Trilinos/packages/ml/src/Main/ml_struct.h(314): error: expected a declaration
  //#include "ml_petsc.h"
  ^

In file included from /home/crtrott/Trilinos/packages/ml/src/Smoother/ml_smoother.h(44),
                 from /home/crtrott/Trilinos/packages/ml/src/Main/ml_1level.h(34),
                 from /home/crtrott/Trilinos/packages/ml/src/Operator/ml_operator.h(33),
                 from /home/crtrott/Trilinos/packages/ml/src/Utils/ml_utils.h(35),
                 from /home/crtrott/Trilinos/packages/ml/src/Utils/ml_memory.c(17):
/home/crtrott/Trilinos/packages/ml/src/Main/ml_struct.h(314): error: "#" not expected here
  //#include "ml_petsc.h"
    ^

In file included from /home/crtrott/Trilinos/packages/ml/src/Smoother/ml_smoother.h(44),
                 from /home/crtrott/Trilinos/packages/ml/src/Main/ml_1level.h(34),
                 from /home/crtrott/Trilinos/packages/ml/src/Operator/ml_operator.h(33),
                 from /home/crtrott/Trilinos/packages/ml/src/Utils/ml_utils.h(35),
                 from /home/crtrott/Trilinos/packages/ml/src/Utils/ml_memory.c(17):
/home/crtrott/Trilinos/packages/ml/src/Main/ml_struct.h(320): warning #12: parsing restarts here after previous syntax error
  		     int ntimes, double omega, int Nextra, int extra[]);

I am not sure why, but maybe its because this clause is in a:

extern "C" {
}

block.

Anyway removing that commented out include fixes my build issues with Intel 15.